; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
  -D MIC_INPUT_MODE=1
  -D MIC_SAMPLE_RATE=16000
  -D MIC_I2S_BCLK=5
  -D MIC_I2S_WS=6
  -D MIC_I2S_DATA=7
  -D MIC_I2S_LEFT_CHANNEL=1
