[platformio]
src_dir = main

[env:esp32-s3-n16r8]
platform = espressif32@6.9.0
board = esp32-s3-n16r8
framework = espidf
monitor_speed = 115200
upload_port = COM11
board_build.partitions = partitions.csv
board_build.flash_size = 16MB
